baseURL = 'https://davidworks.github.io'
languageCode = 'en-us'
title = 'DavidWorks'
theme = 'terminal'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[module]
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/bootstrap'
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/font-awesome'
[params]
  [params.icons]
    throw_on_error = true